#!/bin/sh /etc/rc.common
# vi: ts=4 expandtab

XN=openstack-config

START=99

start() {
	if [ "0"=="$(uci get gluon-setup-mode.@setup_mode[0].configured)" ]
	then
		uci set fastd.mesh_vpn.enabled=1
		uci set fastd.mesh_vpn.secret="$(fastd --generate-key | grep Secret| cut -d' ' -f2)"
		uci set gluon-setup-mode.@setup_mode[0].configured=1
		uci commit
		reboot
	fi
	cat .ssh/authorized_keys > /etc/dropbear/authorized_keys
    return 0
}